### ISSUE TITLE
merge wireguard-manager script with server-firewall script?

### ISSUE THREAD

**Issue by bumansu** [complexorganizations/server-firewall#1]
It is possible to merge wireguard-manager script with server-firewall script?

I installed server-firewall script and then wireguard-manager script, my vpn is not working.

root@ubuntu:~# wg show
interface: wg0
listening port: 48442

**Comment by Prajwal-Koirala** [comment]
it is possible and i can make a small commit on ur foke but not on the main repo.

so if u want me to make a small change just make a fork of my work and ill make the change there.

**Comment by bumansu** [comment]
ok, I fork your repo

**Comment by Prajwal-Koirala** [comment]
> ok, I fork your repo

done.

**Comment by bumansu** [comment]
Do I have to install server-firewall first and then Wireguard-manager?

**Comment by Prajwal-Koirala** [comment]
its all in one.

**Comment by bumansu** [comment]
ok, but witch one? Wireguard script or firewall?
many thanks

**Comment by Prajwal-Koirala** [comment]
https://github.com/bumansu/wireguard-manager-1/pull/2
